### PR TITLE
Added Even/Odd and Length operations

### PR DESCRIPTION
**Pull request by raymo116**

### CODE REVIEW

**Comment by jhburns** [comment]
I'll merge for now, but I think he meant for things to be done as function, not with additional rules.
See https://github.com/jhburns/programming-languages-2019/tree/master/Assignment1#assignment1b
"Implement and run the following functions in LambdNat5"

**Comment by raymo116** [comment]
@jhburns what do you mean as a function?

**Comment by jhburns** [comment]
As in he wants the 'solutions' to be a named function 
For example 
`let rec plus = \x.\y. if x=0 then y else S (plus (minus_one x) y) in plus S S 0 S S S 0`
(taken from his tests) 
is a named function 'plus' that takes in two numbers and adds them together.

Since we implemented head and tales, we shouldn't need any more grammar rules.

**Comment by jhburns** [comment]
@raymo116

**Pull request merged**
